### ISSUE TITLE
openresty1.7.2.1和openresty1.9.3.1对应的nginx官网版本各是哪个？或者openresty是从nginx官网的哪个版本发展起来的？如果官网有重大更新是否会同步过来？

### ISSUE THREAD

**Issue by abirdman** [openresty/openresty.org#19]

**Comment by agentzh** [comment]
@abirdman OpenResty 1.7.2.1 includes NGINX 1.7.2 while OpenResty 1.9.3.1 includes NGINX 1.9.3. You can see the pattern :) Basically, the first 3 digits of OpenResty's version numbers are the NGINX core's version number. You can find more details about OpenResty's release policy below:

http://openresty.org/faq.html#does-openresty-follow-nginxs-mainline-releases

BTW, please do not use Chinese here since this place is considered English only. You're recommended to join the openresty (Chinese) mailing list for such questions. Please see

https://openresty.org/#Community

Thanks for your cooperation :)

**Comment by abirdman** [comment]
OK, thanks very much for your answer!
