### ISSUE TITLE
Doc: Add a link to OpenResty rpm repo?

### ISSUE THREAD

**Issue by spacewander** [openresty/openresty.org#51]
I open the issue here because I consider it is a question about documentation instead of package.

It would be welcome that there is a link to OpenResty's rpm repo description file.
For instance, store `OpenResty.repo` file under a url like `https://reliable.website/OpenResty.repo`.

Instead of copy & distribute, the users are able to run `sudo yum-config-manager --add-repo https://reliable.website/OpenResty.repo` directly to add the repo.

**Comment by agentzh** [comment]
@spacewander This sounds like a good idea. Will you contribute a pull request for this? Thanks!

**Comment by spacewander** [comment]
@agentzh 
No, thanks. I think only the OpenResty maintainer can decide what is a `reliable.website`

**Comment by spacewander** [comment]
Maybe we could put the repo file under `https://openresty.org/`, for instance, `https://openresty.org/yum/OpenResty.repo`?

**Comment by agentzh** [comment]
@spacewander Well, that was the plan. And that's why I was asking you to create a pull request for this openresty.org github repo.

But beware that one complication is that we need different `.repo` files for different versions and kinds of the Linux distributions. See http://openresty.org/en/linux-packages.html

**Comment by agentzh** [comment]
Already done.
