### ISSUE TITLE
Can't I run sanity tests on openresty ?

### ISSUE THREAD

**Issue by chakravarthy392** [openresty/openresty.org#70]
Hi,
Earlier I could install and run sanity test cases on OpeenResty downloaded from [github](https://github.com/openresty/openresty) . Now I have installed Openresty latest version from tar ball provided in [openresty website](https://openresty.org/en/download.html) and could able to check few use cases of Openresty and nginx. Can we execute any other test cases to make sure that OpenResty functionality is correct ?

**Comment by agentzh** [comment]
@chakravarthy392 You'll have to check the Travis CI config files for each OpenResty component since the test suites try to be as comprehensive as possible and are not solely optimized for the ease of running everywhere.

See for example,

https://github.com/openresty/lua-nginx-module/blob/master/.travis.yml

https://github.com/openresty/lua-resty-core/blob/master/.travis.yml

https://github.com/openresty/lua-resty-mysql/blob/master/.travis.yml

Even those Travis CI test files only run the "normal testing mode" of our powerful `Test::Nginx::Socket` test scaffold. The most thorough testing is done in our Amazon EC2 test cluster, leveraging most of the testing modes of `Test::Nginx::Socket`:

https://qa.openresty.org/

The setup and execution commands for this test cluster is encoded in the following opsboy configuration rule file:

https://github.com/openresty/opsboy/blob/master/samples/ortest-ec2.ob.tt

You already have all the info needed to run all the OpenResty tests in all the test modes on your side, I believe :) Good luck!
